# TravisCI config file. See http://travis-ci.org
language: python
python:
  - 2.6
  - 2.7

# command to install dependencies, e.g. pip install -r requirements.txt
install:
  - pip install -r tests/requirements.txt
  - pip install -e git+git://github.com/BigBrotherBot/big-brother-bot.git#egg=b3

# command to run tests, e.g. python setup.py test
script: PYTHONPATH=extplugins nosetests --where=tests
